// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ22B11tOh-MM5PB0rNABuBkOxbpl5ueY',
    appId: '1:249055735676:web:3ff40b55ac77b02fa67ef9',
    messagingSenderId: '249055735676',
    projectId: 'homeease-244623',
    authDomain: 'homeease-244623.firebaseapp.com',
    storageBucket: 'homeease-244623.firebasestorage.app',
    measurementId: 'G-P2N6W8ZJ6F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfhRJct_F8nQWOy5OpH3en-Ev8h5k5Rxk',
    appId: '1:249055735676:android:8f8a16a910149331a67ef9',
    messagingSenderId: '249055735676',
    projectId: 'homeease-244623',
    storageBucket: 'homeease-244623.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPDYzza86ixtpkfc26ZR9mo9X9tfXYm3c',
    appId: '1:249055735676:ios:790f020b7cbb26d8a67ef9',
    messagingSenderId: '249055735676',
    projectId: 'homeease-244623',
    storageBucket: 'homeease-244623.firebasestorage.app',
    iosBundleId: 'com.example.homeease',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPDYzza86ixtpkfc26ZR9mo9X9tfXYm3c',
    appId: '1:249055735676:ios:790f020b7cbb26d8a67ef9',
    messagingSenderId: '249055735676',
    projectId: 'homeease-244623',
    storageBucket: 'homeease-244623.firebasestorage.app',
    iosBundleId: 'com.example.homeease',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQ22B11tOh-MM5PB0rNABuBkOxbpl5ueY',
    appId: '1:249055735676:web:6cc0d465884116f6a67ef9',
    messagingSenderId: '249055735676',
    projectId: 'homeease-244623',
    authDomain: 'homeease-244623.firebaseapp.com',
    storageBucket: 'homeease-244623.firebasestorage.app',
    measurementId: 'G-NBNLYX5DLF',
  );
}
